-- @author myoung
alter table users alter column id bigint generated by default as identity;
alter table user_profile alter column id bigint generated by default as identity;
alter table trip_request alter column id bigint generated by default as identity;
alter table trip_plan alter column id bigint generated by default as identity;
alter table trip_day alter column id bigint generated by default as identity;
alter table trip_item alter column id bigint generated by default as identity;
alter table budget_breakdown alter column id bigint generated by default as identity;
alter table llm_call_log alter column id bigint generated by default as identity;
alter table tool_call_log alter column id bigint generated by default as identity;
