/*
 * @author myoung
 */
package com.aitour;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 验证 Flyway 基础迁移可以从空库创建用户相关表。
 *
 * @author myoung
 */
@SpringBootTest
class DatabaseMigrationTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void shouldCreateUsersTable() {
        Integer count = countPublicTable("users");

        assertThat(count).isEqualTo(1);
    }

    @Test
    void shouldCreateUserProfileTable() {
        Integer count = countPublicTable("user_profile");

        assertThat(count).isEqualTo(1);
    }

    /**
     * 当前测试环境下，核心主表主键应使用数据库 identity/self increment 策略。
     */
    @Test
    void shouldUseIdentityColumnsForCoreTables() {
        assertAutoGeneratedId("users");
        assertAutoGeneratedId("user_profile");
        assertAutoGeneratedId("trip_request");
        assertAutoGeneratedId("trip_plan");
    }

    private Integer countPublicTable(String tableName) {
        return jdbcTemplate.queryForObject(
                "select count(*) from information_schema.tables where table_schema = 'public' and table_name = ?",
                Integer.class,
                tableName
        );
    }

    /**
     * 查询列默认值，供自增主键策略断言使用。
     */
    private String columnDefault(String tableName, String columnName) {
        return jdbcTemplate.queryForObject(
                "select column_default from information_schema.columns where table_schema = 'public' and table_name = ? and column_name = ?",
                String.class,
                tableName,
                columnName
        );
    }

    /**
     * 断言指定表主键列由数据库自动生成。
     */
    private void assertAutoGeneratedId(String tableName) {
        String isIdentity = jdbcTemplate.queryForObject(
                "select is_identity from information_schema.columns where table_schema = 'public' and table_name = ? and column_name = 'id'",
                String.class,
                tableName
        );
        assertThat(isIdentity).isEqualToIgnoringCase("YES");
    }
}
